[build]
  command = "npm run build"
  publish = "dist"

# --- Static assets: cache forever (fingerprinted files) ---
[[headers]]
  for = "/assets/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# --- Root HTML: cache at edge, always revalidate in browser ---
[[headers]]
  for = "/"
  [headers.values]
  Cache-Control = "public, s-maxage=300, max-age=0, stale-while-revalidate=600"

# --- API JSON endpoints (Astro/WP proxyed responses) ---
[[headers]]
  for = "/wp-json/astro/v1/*"
  [headers.values]
  Cache-Control = "public, s-maxage=300, max-age=0, stale-while-revalidate=600"

# --- GF Submit (POST only, but protect against accidental GET) ---
[[headers]]
  for = "/wp-json/astro/v1/gf/submit"
  [headers.values]
  Cache-Control = "no-store"

# --- Security headers ---
[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
